activ_fun: tanh
alpha: null
batch_size: 32
batched: false
beta: null
bias: null
constant_feature: null
conv_layer: null
convergence_log: null
cosine_T0: 25
d_state: 64
dampening_mode: null
delay: null
device: gpu
diversity_plot_dir: null
doubled_dim: null
dropout: 0.0
enable_timing: false
epsilon: 0.1
es_patience: 100
external_mode: null
final_state: null
gamma: 0.1
glgsm_mode: hyper
gnn_type: GenLGSM
graph_conv: GCNConv
hidden_dim: 64
hyper_hidden_dim: 128
input_dim: 2
khop: null
lr: 0.0001
lr_min: 1.0e-06
lr_scheduler: none
max_epochs: 1000
max_lr: null
node_level_task: true
num_layers: 4
num_steps: 40
output_dim: 1
p_conv_mode: null
q_conv_mode: null
scaling_factor: 40.0
scheduler_patience: 20
selective: false
task: ecc
timing_csv_base_path: training_timings
train_weights: null
wandb: false
weight_decay: 0.0
weight_sharing: null
window_size: 2
